version: '3.8'

# Define services
services:
  # App Service
  app:
    # Configuration for building the docker image for the service
    image: stasundr/swarm-backend:0.0.2
    ports:
      - '8080:8080' # Forward the exposed port 8080 on the container to port 8080 on the host machine
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - swarmband

networks:
  swarmband:
    driver: overlay
    attachable: true
